config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }, path_names: {
    sign_in: 'log_in',
    sign_up: 'create_account',
    sign_out: 'logout'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]

  namespace :api , defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: { message: 'Title must not be blank' },
                    length: { maximum: 250, too_long: 'Title must not exceed 250 characters' }
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal: 0

  after_create :update_post_counter
  after_destroy :update_post_counter_after_destroy
  before_validation :trim_text

  def update_post_counter
    user.update_column('posts_counter', user.posts_counter + 1)
  end

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def update_post_counter_after_destroy
    user.update_column('posts_counter', user.posts_counter - 1)
  end

  private

  def trim_text
    self.title = title.strip if title.present?
    self.text = text.strip if text.present?
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      load_and_authorize_resource

      def index
        @posts = Post.order(:created_at)
        render json: { success: true, message: 'Loaded all posts', data: { posts: @posts } }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.top_most_recent_posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    new_post = Post.new(post_params)
    current_user.posts << new_post
    if new_post.save
      flash[:notice] = 'Post created!'
      redirect_to user_posts_path(new_post.user.id)
    else
      flash.now[:alert] = 'Failed to create post!'
      render :new
    end
  end

  def destroy
    post_to_delete = Post.find(params[:id])
    owner = post_to_delete.user
    if post_to_delete.destroy
      flash[:notice] = 'Post destroyed successfully!'
    else
      flash[:alert] = 'Unable to delete post'
    end
    redirect_to user_posts_path(owner.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_card.html.erb
<ul class="comment__list">
  <% comments_with_user(comments).each do |c| %>
    <li class="comment__item">
      <span class="comment__item-user"><%= c.user.name  %>:  </span>
      <span class="comment__item-comment"><%= c.text %> </span>
      <div class="trash__container">
        <% if can? :destroy, c %>
          <%= button_to comment_path(c.id), method: :delete, class: "trash-btn" do %>
            <i class='bx bx-trash-alt box-icon'></i>
          <% end %>
        <% end %>
      </div>
    </li>
    <hr />
  <% end %>
</ul>

app/views/posts/_comment_form.html.erb
<div class="form__container">
  <%= form_with url: post_comments_path(post.id), scope: :data do |f| %>
    <div class="field">
      <%= f.text_area :text, size: "60x10", required: true, placeholder: "Write comment...", class: "text_area" %>
    </div>
    <%= f.submit "Comment", class: "btn" %>
  <% end %>
</div>

app/views/posts/_like_view.html.erb
<div class="like__container">
  <% if post_liked_by?({ post: post, id: current_user.id }) %>
    <i class="bx bx-check like-btn box-icon"></i>
  <% else %>
    <%= button_to post_likes_path(post.id), class: "like-btn", method: :post do %>
      <i class="bx bxs-like like-btn box-icon"></i>
    <% end %>
  <% end %>
</div>

app/views/posts/_no_of_comments.html.erb
<span><%= t("post.comments", count: total_comments) %></span>

app/views/posts/_no_of_likes.html.erb
<span> <%= t("post.likes", count: total_likes) %></span>

app/views/posts/_post_card.html.erb
<div class="post mb-2 mt-2">
  <div class="post__header">
    <%= link_to user_post_path(@user.id, post.id), id: "user_post#{post.id}" do %>
      <h5 class="post__title"><%= capitalize(post.title) %></h5>
    <% end %>
    <% if can? :destroy, post %>
      <%= button_to post_path(post.id), method: :delete, class: "trash-btn" do %>
        <i class='bx bx-trash-alt box-icon'></i>
      <% end %>
    <% end %>
  </div>
  <p class="post__text"><%= shorten_text(post.text) %>  </p>
  <div class="post__likes_comments_counter">
    <%= render partial: "posts/no_of_comments", locals: { total_comments: post.comments_counter } %>, <%= render partial: "posts/no_of_likes", locals: { total_likes: post.likes_counter } %>
  </div>
</div>

app/views/posts/_post_with_comment_card.html.erb
<li class="post__comment-item mb-2">
   <%= render partial: "post_card", locals: { post: post } %>
  <% if can_display_comments?(post.comments_counter) %>
    <%= render partial: "comment_card", locals: { comments: post.most_recent_comments } %>
  <% end %>
</li>

app/views/posts/index.html.erb
<div class="profile__container">
  <%= render partial: "users/user_card", locals: { user: @user } %>
    <ul class="post__comment">
      <% @posts.each do |p| %>
        <%= render partial: "post_with_comment_card", locals: { post: p } %>
      <% end %>
    </ul>
  <button class="btn">Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="form__container">
  <%= form_with url: posts_path, model: @post do |f| %>
    <h6 class="form__header">Create new post</h6>
    <div class="field">
      <%= f.text_field :title, class: "input", required: true, placeholder: "Title", value: nil %>
    </div>
    <div class="field">
      <%= f.text_area :text, size: "60x10", required: true, placeholder: "Write text here...", value: nil, class: "text_area" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="profile__container">
  <div class="post">
    <div class="header">
      <%= link_to user_posts_path(@user.id) do %>
        <h5 class="post__title"><%= capitalize(@post.title) %> by <%= capitalize(@user.name) %></h5>
      <% end %>
      <div class="post__likes_comments_counter">
        <%= render partial: "posts/no_of_comments", locals: { total_comments: @post.comments_counter } %>, <%= render partial: "posts/no_of_likes", locals: { total_likes: @post.likes_counter } %>
      </div>
    </div>
    <div class="like__container">
      <% if can? :destroy, @post %>
        <%= button_to post_path(@post.id), method: :delete, class: "trash-btn" do %>
          <i class='bx bx-trash-alt box-icon'></i>
        <% end %>
      <% end %>
      <%= render partial: "like_view", locals: { post: @post } %>
    </div>
    <p class="post__text"><%= @post.text %> </p>
  </div>
  <% if can_display_comments?(@post.comments_counter) %>
    <%= render partial: "comment_card", locals: { comments: @post.comments } %>
  <% end %>
  <%= render partial: "comment_form", locals: { post: @post } %>

</div>